const actionTypes = {
   GET_POST_REQUEST: 'GET_POST_REQUEST',
   GET_POST_SUCCESS: 'GET_POST_SUCCESS',
   GET_POST_FAIL: 'GET_POST_FAIL',

   SHOW_MODAL: 'SHOW_MODAL',
   HIDE_MODAL: 'HIDE_MODAL',

   CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
   CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
   CREATE_POST_FAIL: 'CREATE_POST_FAIL',

   UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
   UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
   UPDATE_POST_FAIL: 'UPDATE_POST_FAIL',

   DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
   DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
   DELETE_POST_FAIL: 'DELETE_POST_FAIL'
}

export default actionTypes
